### ISSUE TITLE
kpm整体流程探讨

### ISSUE THREAD

**Issue by shepherdwind** [kissygalleryteam/kpm#1]
这里主要探讨下kpm工具运行的过程，分为两部分，第一部分，用户如何使用，第二部分kpm的内部整合机制。下面主要是我的一些意见，大家看看有木有问题。
### 命名

kpm工具这一块，我觉得kpm这个名字不是很友好，我觉得整个项目需要一个类似于YUI Gallery的yogi那样霸气的名字，做成一个项目，首先需要一个好玩的名字。我想了一个`jear`，意义是升帆的绳子，感觉还有点贴切。不过这个看大家讨论的结果了，这个名字我在npm上站位了，在我自己的repo下创建了这么一个库，因为还没确定，没有放到kpm上来，大家感受下怎么样:)。
### Github api机制

因为最终我们的代码是放在github上的，这几天主要研究了一下github api的使用方案。通常的流程是这样的，在web端，开发者申请一个app，用户通过一个授权的链接选择授权。在非web端，比如github的安卓客户端，用户首先登陆，然后工具在用户创建一个授权的applications，这个过程不需要用户再次确认，github返回一个token，以后通过token就可以执行在github上的所有操作。这个token通常保存在用户本地，这个东东如果泄露，其他人也能随意操作对应人的github账户了。
### 用户使用过程

根据上面的github的api机制，我们不能让用户直接提交代码到kpm上，但是用户可以授权kpm工具，我们可以帮他提交代码、发pull请求等等操作，不过都只限于对用户自己的账户的操作。

我想到的工作模式是，用户登陆github，授权kpm工具，如果没有账户先注册一个，创建一个gallery module是，执行init modulename，init需要的文件，执行commit或者publish时，如果用户的github上没有对应的库，创建库，并且提交代码，同时把代码推送到kpm服务器上，或者让kpm服务器向kpm的github下创建一个同名的repo，publish时发送一个pull请求。

用户发送推送cdn请求是，kpm服务器接受到请求，由承玉或者其他人审核，审核通过，自动发布/gallery库自动提交或者merge。
### 工具内部组织

kpm工具主要是一个命令行工具，所有的命令通过`addCommand`来注册，使用插件的机制。`addCommand`执行如下：

``` js
exports.cli = function(program){

  program.
    command('login').
    description('login for github use').
    //option("-f, --setup_mode [mode]", "Which setup mode to use").
    action(function(env){
      //var mode = options.login_mode || "normal";
      Login.login();
    });

  return program;

};
```

`program`是npm模块`commander`来实现的。上面的命令，效果是执行`kpm`自动注册一个command，执行`kpm login`，会执行上面的action对应的函数。

command之间使用api `getCommand`来获取。

这是我这几天主要成果，欢迎大家提出意见和建议。

**Comment by minghe** [comment]
顶翰文。

关于命名：kpm是工具项目代号民，并不是工具名，也不是命令行起始命令名。同意改成好玩的名字，不过提一点，单词控制下四个字母，因为工具名也是命令名。

github问题：之前定下的方案是，用户提交代码到我们的公共服务器上，跟你说push到github上有冲突吗？二者是如何共存？

用户使用过程：感觉流程有些长，能再做简化吗？

**Comment by shepherdwind** [comment]
关于用户使用流程，我梳理一下：

### 安装准备、依赖：
1. 一个github账户
2. 安装git命令行工具

如果用户没有github账户的情况下，我的想法是，让用户创建账户，kpm的网站上账户使用github的api，这样就不需要另外一套账户系统了。另外，可以考虑issue和kpm的网站和对于repo上就行双向同步。

用户提交代码到公共服务器上，但最终还是会发到github上，只是用户直接提交到公共服务器上，我们再把代码发到github上。最终代码还是通过git库贮存的。

### 安装过程：

```
npm install -g kpm
```

### 安装初始化：

`kpm setup` 让用户登陆github 账户，并且检测是否有安装git目录工具，没有则提示之。

### 使用过程

``` sh

//第一步
kpm init app //创建app

//第二步
//write code

//第三步
kpm commit | kpm pushcdn

//其他，查看状态等等
kpm status
```

上面过程中，commit和pushcdn分别是发布到官方github repo的请求，如果是pushcdn的话，成功后服务器自动同步到cdn上。

**Comment by yiminghe** [comment]
grunt 插件的方案不做了？自己和基于 grunt 有什么优势？

**Comment by shepherdwind** [comment]
做了一个图片。grunt我得再研究下，如果基于grunt，还是得需要一个把所有命令整合的工具。

![kpm](https://f.cloud.github.com/assets/452899/199624/a88a8eb4-8093-11e2-98ea-70ce19e2c499.png)

**Comment by shepherdwind** [comment]
此方案废弃。

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-10-10T15:23:32 
pubish files: 
/assets/s/kissy/gallery/page/1.0/index-min.js
/assets/s/kissy/gallery/page/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>182</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-10-11T12:15:53 
pubish files: 
/assets/s/kissy/gallery/droplist/0.1/index-min.js
/assets/s/kissy/gallery/droplist/0.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>190</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>6</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-10-16T16:52:31 
pubish files: 
/assets/s/kissy/gallery/koo/1.0/index-min.css
/assets/s/kissy/gallery/koo/1.0/index.css
/assets/s/kissy/gallery/koo/1.0/index-min.js
/assets/s/kissy/gallery/koo/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>187</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-12-25T10:28:27 
pubish files: 
/assets/s/kissy/gallery/formalize/0.1/index-min.js
/assets/s/kissy/gallery/formalize/0.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 3s</td>        <td>199</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>1</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-22T17:25:15 
pubish files: 
/assets/s/kissy/gallery/formalize/0.1/index.js
/assets/s/kissy/gallery/formalize/0.1/index-min.js 
```

  <strong>publish status</strong>
pull url: https://github.com/kissygalleryteam/formalize/pull/1  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 2s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>40</td>      </tr>            <tr>        <td>online</td>        <td>679h 6min 51s</td>        <td>160</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-22T18:11:57 
pubish files: 
/assets/s/kissy/gallery/formalize/0.1/index.js
/assets/s/kissy/gallery/formalize/0.1/index-min.js 
```

  <strong>publish status</strong>
pull url: https://github.com/kissygalleryteam/formalize/pull/2  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>198</td>      </tr>            <tr>        <td>online</td>        <td>56min 44s</td>        <td>2</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-27T17:50:23 
pubish files: 
/assets/s/kissy/gallery/formalize/0.1/index.js
/assets/s/kissy/gallery/formalize/0.1/index-min.js 
```

  <strong>publish status</strong>
pull url: https://github.com/kissygalleryteam/formalize/pull/3  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 4s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 4s</td>        <td>200</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-11T15:38:56 
pubish files: 
/assets/s/kissy/gallery/formalize/0.1/index.js
/assets/s/kissy/gallery/formalize/0.1/index-min.js 
```

  <strong>publish status</strong>
pull url: https://github.com/kissygalleryteam/formalize/pull/4  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 2s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>197</td>      </tr>            <tr>        <td>online</td>        <td>357h 58min 37s</td>        <td>3</td>      </tr>      </tbody></table>
