### ISSUE TITLE
add RichDate

### ISSUE THREAD

**Issue by hirokith** [kissygalleryteam/kpm#108]
https://github.com/dickeylth/RichDate

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-09T11:43:40 
pubish files: 
/assets/s/kissy/gallery/RichDate/1.0/index-min.js
/assets/s/kissy/gallery/RichDate/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>178</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>6</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-10T14:50:58 
pubish files: 
/assets/s/kissy/gallery/RichDate/1.1/index-min.js
/assets/s/kissy/gallery/RichDate/1.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>178</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>6</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-11T20:26:33 
pubish files: 
/assets/s/kissy/gallery/RichDate/1.1/index-min.js
/assets/s/kissy/gallery/RichDate/1.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>178</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>6</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-11T21:26:20 
pubish files: 
/assets/s/kissy/gallery/RichDate/1.1/index-min.js
/assets/s/kissy/gallery/RichDate/1.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>177</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-16T19:36:35 
pubish files: 
/assets/s/kissy/gallery/RichDate/1.1/index-min.js
/assets/s/kissy/gallery/RichDate/1.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 8s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 9s</td>        <td>175</td>      </tr>            <tr>        <td>online</td>        <td>118h 20min 21s</td>        <td>1</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>8</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-05-04T12:08:39 
pubish files: 
/assets/s/kissy/gallery/RichDate/1.1/index.js
/assets/s/kissy/gallery/RichDate/1.1/index-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 8s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 9s</td>        <td>173</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>13</td>      </tr>      </tbody></table>
