### ISSUE TITLE
add sapper

### ISSUE THREAD

**Issue by chishang** [kissygalleryteam/kpm#110]
勤奋的挖掘工，快速找出页面入口

https://github.com/chishang/sapper

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-12T16:18:27 
pubish files: 
/assets/s/kissy/gallery/sapper/1.0/index-min.css
/assets/s/kissy/gallery/sapper/1.0/index.css
/assets/s/kissy/gallery/sapper/1.0/index-min.js
/assets/s/kissy/gallery/sapper/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>178</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-16T13:06:27 
pubish files: 
/assets/s/kissy/gallery/sapper/2.0/index-min.css
/assets/s/kissy/gallery/sapper/2.0/index.js
/assets/s/kissy/gallery/sapper/2.0/index-min.js
/assets/s/kissy/gallery/sapper/2.0/index.css 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>177</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-17T10:36:25 
pubish files: 
/assets/s/kissy/gallery/sapper/1.1/index-min.css
/assets/s/kissy/gallery/sapper/1.1/index.js
/assets/s/kissy/gallery/sapper/1.1/index-min.js
/assets/s/kissy/gallery/sapper/1.1/index.css 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>173</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>6</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-17T11:23:53 
pubish files: 
/assets/s/kissy/gallery/sapper/1.1/index-min.js
/assets/s/kissy/gallery/sapper/1.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>174</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>6</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-10-28T16:21:19 
pubish files: 
/assets/s/kissy/gallery/sapper/1.1/index.js
/assets/s/kissy/gallery/sapper/1.1/index-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 8s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 8s</td>        <td>191</td>      </tr>            <tr>        <td>online</td>        <td>989h 7min 31s</td>        <td>5</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>4</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-11-06T17:41:01 
pubish files: 
/assets/s/kissy/gallery/sapper/1.2/index-min.css
/assets/s/kissy/gallery/sapper/1.2/index.js
/assets/s/kissy/gallery/sapper/1.2/index-min.js
/assets/s/kissy/gallery/sapper/1.2/index.css 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>N/A</td>        <td>200</td>      </tr>      </tbody></table>
