### ISSUE TITLE
add pwdstrength

### ISSUE THREAD

**Issue by hirokith** [kissygalleryteam/kpm#141]
https://github.com/dickeylth/pwdstrength

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-09-26T13:52:52 
pubish files: 
/assets/s/kissy/gallery/pwdstrength/1.0/index-min.css
/assets/s/kissy/gallery/pwdstrength/1.0/index.css
/assets/s/kissy/gallery/pwdstrength/1.0/index-min.js
/assets/s/kissy/gallery/pwdstrength/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>175</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-20T17:31:28 
pubish files: 
/assets/s/kissy/gallery/pwdstrength/1.0/index-min.css
/assets/s/kissy/gallery/pwdstrength/1.0/index.css
/assets/s/kissy/gallery/pwdstrength/1.0/index-min.js
/assets/s/kissy/gallery/pwdstrength/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 1s</td>        <td>196</td>      </tr>            <tr>        <td>online</td>        <td>3531h 48min 42s</td>        <td>4</td>      </tr>      </tbody></table>
