### ISSUE TITLE
add KSortTable

### ISSUE THREAD

**Issue by ccforward** [kissygalleryteam/kpm#192]
https://github.com/ccforward/KSortTable

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-10-22T16:11:49 
pubish files: 
/assets/s/kissy/gallery/KSortTable/1.0/index-min.js
/assets/s/kissy/gallery/KSortTable/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>185</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>7</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-20T17:33:50 
pubish files: 
/assets/s/kissy/gallery/KSortTable/1.0/index-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>191</td>      </tr>            <tr>        <td>online</td>        <td>2905h 32min 6s</td>        <td>8</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>1</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-20T17:39:19 
pubish files: 
/assets/s/kissy/gallery/KSortTable/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>188</td>      </tr>            <tr>        <td>online</td>        <td>2905h 37min 35s</td>        <td>12</td>      </tr>      </tbody></table>
