### ISSUE TITLE
api接口

### ISSUE THREAD

**Issue by shepherdwind** [kissygalleryteam/kpm#2]
所有接口汇总
### 用户创建 Get

参数：
1. token
2. username
3. tokenId
4. email

返回:

success: https://gist.github.com/shepherdwind/5149330#file-user-create-ok
error: https://gist.github.com/shepherdwind/5149330#file-user-create-error
### 用户信息获取

参数：Get
1. name

返回：

success: https://gist.github.com/shepherdwind/5149330#file-user-ok
error: https://gist.github.com/shepherdwind/5149330#file-user-no
### package信息获取Get

参数：
1. packageName

返回：

success: https://gist.github.com/shepherdwind/5149330#file-package-ok
error: https://gist.github.com/shepherdwind/5149330#file-package-no
### gallery fork用户的库

参数：
1. username
2. appname
3. token
4. tokenId

返回：

success: https://gist.github.com/shepherdwind/5149330#file-success
error: https://gist.github.com/shepherdwind/5149330#file-error
### 改变package状态为merge请求

参数：
1. tokenId
2. username
3. appname

返回：

success: https://gist.github.com/shepherdwind/5149330#file-success
error: https://gist.github.com/shepherdwind/5149330#file-error

**Comment by shepherdwind** [comment]
这是所有的接口，和对应的返回。@feichang 看下。

**Comment by shepherdwind** [comment]
有什么需要修改的，直接修改，然后通知一下我就可以。

**Comment by ghost** [comment]
@shepherdwind 测试一下
