### ISSUE TITLE
add tb-video-player

### ISSUE THREAD

**Issue by xiaosong** [kissygalleryteam/kpm#217]
https://github.com/xiaosong/tb-video-player

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-12-03T10:49:07 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.0/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>197</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>3</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-12-03T11:05:51 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.0/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 1s</td>        <td>197</td>      </tr>            <tr>        <td>online</td>        <td>26min 46s</td>        <td>1</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>2</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-06T13:12:11 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.1/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 4s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 4s</td>        <td>200</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-13T10:08:47 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.2/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.2/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>198</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>2</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-16T16:23:43 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.3/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.3/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 1s</td>        <td>199</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>1</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-16T16:47:02 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.3/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.3/index.js
/assets/s/kissy/gallery/tb-video-player/1.3/core/swf.js
/assets/s/kissy/gallery/tb-video-player/1.3/core/swf.js
/assets/s/kissy/gallery/tb-video-player/1.3/core/swf-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>198</td>      </tr>            <tr>        <td>online</td>        <td>33min 20s</td>        <td>2</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-16T17:33:03 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.3/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.3/core/swf.js
/assets/s/kissy/gallery/tb-video-player/1.3/core/swf.js
/assets/s/kissy/gallery/tb-video-player/1.3/core/swf-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>200</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-22T18:45:44 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.4/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.4/index.js
/assets/s/kissy/gallery/tb-video-player/1.4/core/swf.js
/assets/s/kissy/gallery/tb-video-player/1.4/core/swf.js
/assets/s/kissy/gallery/tb-video-player/1.4/core/swf-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>200</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-22T19:01:21 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.4/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.4/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>200</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-01-22T19:19:04 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.4/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.4/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>200</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-13T12:53:04 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.4/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.4/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 2s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>195</td>      </tr>            <tr>        <td>online</td>        <td>521h 44min 2s</td>        <td>5</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-20T17:32:39 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.5/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.5/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 1s</td>        <td>192</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>8</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-03-03T16:42:19 
pubish files: 
/assets/s/kissy/gallery/tb-video-player/1.5/index-min.js
/assets/s/kissy/gallery/tb-video-player/1.5/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 6s</td>        <td>178</td>      </tr>            <tr>        <td>online</td>        <td>263h 19min 41s</td>        <td>7</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>13</td>      </tr>      </tbody></table>
