### ISSUE TITLE
github上无法fork至@kissygalleryteam

### ISSUE THREAD

**Issue by wylking2000** [kissygalleryteam/kpm#232]
https://github.com/wylking2000/layer-slider库无法fork至@kissygalleryteam，求帮助~

**Comment by minghe** [comment]
亲的花名是什么？联系我旺旺剑平

**Comment by minghe** [comment]
请按照教程里面来，提交issue，我这边会review fork

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-12T11:11:07 
pubish files: 
/assets/s/kissy/gallery/tmpl/1.0/index-min.js
/assets/s/kissy/gallery/tmpl/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>197</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>3</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-02-12T16:15:41 
pubish files: 
/assets/s/kissy/gallery/tmpl/1.0.1/index-min.js
/assets/s/kissy/gallery/tmpl/1.0.1/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>197</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>3</td>      </tr>      </tbody></table>
