### ISSUE TITLE
 kpm流程2.0版

### ISSUE THREAD

**Issue by shepherdwind** [kissygalleryteam/kpm#4]
kpm流程改版，现在kpm成为一个web服务，不需要任何本地工具了。

前提条件，用户拥有github账户，并且能够自行把代码提交到github上去。

我们假设用户需要开发一个Kissy的一个模块，模块名是app，完整流程如下：
## 加入kpm官方库

第一步：用户创建repo：app，然后在app的webhook中加入kpm的一个url (webhook)。这时候意味着，用户的app请求和kissy的gallery建立关系。

第二步：用户在kpm官方库中创建一个issue，请求加入kpm，带上repo的地址，kpm管理员把用户的app folk一份到kpm官方库中去。或者用户在配置hook之后，提交一个commit，注释中如果含有`add to kpm`，那么自动在kpm库中创建一个issue。管理员手动folk用户的app，这时候表示gallery接受用户的库app。

预发：用户编写代码，提交一个commit注释信息包含`pre publish to cdn`，那么当前提交自动发布到预发环境。

发布：正式发布有两种方式
1. merge过程，需要管理员审核，用户把自己的代码发一个pull request到kpm官方库中，当这个merge被接受，那么自动发布。
2. tag过程，用户自行发布，用户把自己的repo创建一个tag，tag表示版本信息，每次更新一个tag，这种方案的前提是用户的repo被官方库授权自行发布。授权过程是在kpm库中的一个文件auth.json中加入授权名单。

第二种发布过程可以如下表示：

``` sh
$ git tag 0.1.0 -m ‘publish version 0.1.0’
$ git push origin 0.1.0
```
## kpm需要做的

webhook服务。hook服务的数据通过git库管理，库的名字叫kpm，是kpm的系统库，主要kpm相关的issue讨论和web服务的数据存储。在kpm下有一个modules.json文件。记录搜有的模块，默认模块都是不允许自动发布的。hook服务只需要做预发和发布两个过程，并且处理一些发布的逻辑，比如判断发过来的hook请求是否被gallery官方通过，判断是否需要预发布，在用户通过tag方案来发布的时候，把用户的代码merge到官方库上去。
## 这种方案的优势与问题

优势，方案非常简单，基本上下周一就可以投入使用，对与用户来说，只需要一个github账户，提交即发布，提交代码就是kpm服务的使用过程，通过约定，而已把原来的方案中用户层、github管理层全部省略，只有一个自动发布和代码关系处理。问题，对一些用户来说，如果不清楚github的使用，需要简单的培训。

**Comment by shepherdwind** [comment]
除了上面的webhook服务之外，另外开发两个grunt相关的插件

``` sh
# 初始化一个kpm模块
$ grunt-init kpm
# 发布状态
$ grunt status
```

status用于查看发布状态，发布时间记录在gallery的官方库上面。

**Comment by yiminghe** [comment]
grunt 插件部分整合到 abc 吧，

**Comment by shepherdwind** [comment]
考虑到安全问题，加上token机制来进行检验。token从内网生成，生成规则由时间，私有密钥加上模块名三者加密决定。

**Comment by shepherdwind** [comment]
Abc现在基于grunt，grunt插件可以无缝接入的。
在 2013-3-27 下午9:14，"yiminghe" notifications@github.com写道：

**Comment by shepherdwind** [comment]
补充一下，另外一个关键点，用户的库加入到gallery官方库，这个时候必须在kpm的库下建一个issue，然后说明一下需要合并的repo的url地址，这个issue后面还会作为发布状态通知的消息中心。

**Comment by shepherdwind** [comment]
还是不行，外网服务器无法访问内网。自动发布不可能做到。可以做到的只是定时同步，现在还有一个问题就是现在svn同步的方案基本是要放弃了的，而我们现在做自动发布只能够是通过svn来同步。我先搞一个svn发布版本，grunt插件的吧。
