### ISSUE TITLE
add aop

### ISSUE THREAD

**Issue by kingback** [kissygalleryteam/kpm#53]
添加AOP模块

**Comment by kingback** [comment]
done

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-06-06T12:23:22 
pubish files: 
/assets/s/kissy/gallery/aop/1.0/index-min.js
/assets/s/kissy/gallery/aop/1.0/index.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>118</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>2</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-06-07T17:03:01 
pubish files: 
/assets/s/kissy/gallery/aop/1.0/index-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>117</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>3</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2013-12-23T20:15:54 
pubish files: 
/assets/s/kissy/gallery/aop/1.0/index.js
/assets/s/kissy/gallery/aop/1.0/index-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 1s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 2s</td>        <td>98</td>      </tr>            <tr>        <td>online</td>        <td>4808h 2min 37s</td>        <td>102</td>      </tr>      </tbody></table>

**Comment by kissygallery** [comment]
<strong>publish recode</strong> 

```
publish Time: 2014-04-10T14:59:37 
pubish files: 
/assets/s/kissy/gallery/aop/1.1/mini.js
/assets/s/kissy/gallery/aop/1.1/index-min.js
/assets/s/kissy/gallery/aop/1.1/index.js
/assets/s/kissy/gallery/aop/1.1/mini-min.js 
```

  <strong>publish status</strong>
  <table>    <thead>      <tr>        <th>status</th>        <th>pass time</th>        <th>num</th>      </tr>    </thead>    <tbody>    <tr>      <td>publish</td>      <td>10min 5s</td>      <td>all</td>    </tr>        <tr>        <td>online</td>        <td>10min 5s</td>        <td>183</td>      </tr>            <tr>        <td>online</td>        <td>N/A</td>        <td>13</td>      </tr>      </tbody></table>
